version: '3.8'

services:
  netatmo-exporter:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NETATMO_CLIENT_ID=${NETATMO_CLIENT_ID}
      - NETATMO_CLIENT_SECRET=${NETATMO_CLIENT_SECRET}
      - NETATMO_EXPORTER_PORT=8000
      - NETATMO_EXPORTER_REFRESH_INTERVAL=300
    networks:
      netatmo-network:
        ipv4_address: 192.168.1.50
      bridge:

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      netatmo-network:
        ipv4_address: 192.168.1.51

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      netatmo-network:
        ipv4_address: 192.168.1.52
      bridge:

volumes:
  grafana_data:
    driver: local

networks:
  netatmo-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
  bridge:
    driver: bridge